### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by philip-crawford** [tinymce/oxide#1]
The install command as listed in the readme is currently failing with this output.
NPM version 6.9.0
Node 10.16.0
Red Hat Enterprise Linux Server release 7.6 (Maipo)

$ npm install

> @ephox/bedrock@4.3.0 preinstall ~/tinymce.skin/node_modules/@ephox/bedrock
> node -e "if(process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('You must use Yarn to install, not NPM')"

[eval]:1
if(process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('You must use Yarn to install, not NPM')
                                                    ^

Error: You must use Yarn to install, not NPM
    at [eval]:1:59
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at evalScript (internal/bootstrap/node.js:589:27)
    at startup (internal/bootstrap/node.js:265:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN @tinymce/oxide@1.0.150 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux ","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ephox/bedrock@4.3.0 preinstall: `node -e "if(process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('You must use Yarn to ins tall, not NPM')"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ephox/bedrock@4.3.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-06-18T00_34_25_927Z-debug.log

**Comment by TheSpyder** [comment]
Sorry, this whole repository (and the documentation pointing to it) is in the process of being re-linked to the TinyMCE monorepo:
https://github.com/tinymce/tinymce/tree/master/modules/oxide

We switched to a Yarn Workspace so NPM can't be used, hence the error message.

I've been away since that was merged; I will remove the source code that was pulled into the monorepo this week.
